import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Fotter from '@/components/common/Fotter';
import Header from '@/components/common/Header';
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen justify-between'>
          <Header />
          <div className='py-4 my-auto grow'>{children}</div>
          <SpeedInsights />
          <Fotter />
        </div>
      </body>
    </html>
  );
}
